#!/sbin/sh -Tue -

stty status '^T'

trap : 2

HOME=/
PATH=/sbin:/bin:/usr/sbin:/usr/bin

export PATH HOME

MAKEINIT="make -D AUTOBOOT -C /etc/mrc -k"
NCPU=$((`/sbin/sysctl -n hw.ncpu` + 1 ))
#MAKEDEBUG="-d -nelLx"

if mkdir -p /etc/mrc/tmp && mount -t tmpfs tmpfs /etc/mrc/tmp; then
  ${MAKEINIT} -j ${NCPU} ${MAKEDEBUG} -X TMPDIR=/etc/mrc/tmp && umount -f /etc/mrc/tmp
else
  ${MAKEINIT}
fi

echo ''
date
exit 0
